---

include:
  - project: 'python/packaging'
    ref: develop
    file: 'gitlab/pyproject-create-all.yaml'

# ---------------------------
# Global variables
variables:
  # DEBFULLNAME: 'Frank Brehm'
  # DEBEMAIL: 'frank@brehm-online.com'
  EXPIRE_ARTIFACTS_IN: '1 week'
  # FB_REPOSERVER_URL: 'http://repo.uhu-banane.de'
  # FB_REPOSERVER_GPGKEY_URL: 'http://repo.uhu-banane.de/public/repo.uhu-banane.de.gpg-key2.asc'
  # NOTIFY_ADDRESS: 'frank.brehm@pixelpark.com'
  PKG_NAME: 'fb-logging'
  PYTHON_INIT_FILE: 'lib/fb_logging/__init__.py'
  # PYTHON_TEST_PATHS: 'src'
  # SENDER_ADDRESS: 'gitlab-ci@pixelpark.com'
  SHELLSCRIPTS: 'get-debian-version get-rpm-release get-rpm-version'
  SSH_PRIV_KEY_YUM_REPO: 'nada'
  TEST_LOCALES: 'en_US.UTF-8'
  UPDATE_ALL_PIP_MODULES: 'y'
  USED_SSH_PRIV_KEY_YUM_REPO: "${SSH_PRIV_KEY_YUM_REPO}"
  USED_YUM_REPO_GPG_PASSWD: "${YUM_REPO_GPG_PASSWD}"
  USED_YUM_REPO_GPG_KEY_PUB: "${YUM_REPO_GPG_KEY_PUB}"
  USED_YUM_REPO_GPG_KEY_SEC: "${YUM_REPO_GPG_KEY_SEC}"
  USED_TIMEZONE: 'Europe/Berlin'
  # VERSION_PREFIX: 'unknown'
  YUM_REPO_GPG_ID: 'C0E73F70'
  YUM_REPO_GPG_PASSWD: ''
  # YUM_REPO_HOST: 'repo.pixelpark.com'
  # YUM_REPO_USER: 'rpm-repo'
  # YUM_REPO_DIR_HTTP: '/Linux/yum/pixelpark'
  # YUM_REPO_DIR: "/srv/www/repo${YUM_REPO_DIR_HTTP}"
  YUM_REPO_GPG_KEY_PUB: 'nada'
  YUM_REPO_GPG_KEY_SEC: ''
  REVISION: 78

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
