---

runs:
  using: "composite"
  steps:
    - name: Update all packages
      id: apt-update
      shell: bash
      run: |
        echo "Apt update ..."
        apt update --yes
        echo "Apt list upgradeable ..."
        apt list --upgradeable
        echo "Apt dist-upgrade ..."
        echo "::group::APT dist-upgrade"
        apt dist-upgrade --yes
        echo "::endgroup::"

    - name: Install locales and gettext
      id: install-gettext
      shell: bash
      run: |
        echo "Installing sudo, locales and gettext"
        echo "::group::APT install 10n"
        apt install --yes sudo locales gettext
        echo "::endgroup::"

    - name: Update Locales
      id: update-locales
      shell: bash
      run: |
        echo "Current available locales:"
        locale -a
        if test -f /etc/locale.gen; then
          echo "Current /etc/locale.gen:"
          grep -P -v '^\s*(#.*)?$' /etc/locale.gen || true; echo "<-- EOF"
        fi
        echo "Ensuring 'en_US.UTF-8' ..."
        if grep 'en_US.UTF-8' /etc/locale.gen; then
          sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
        else
          echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
        fi
        echo "Ensuring 'de_DE.UTF-8' ..."
        if grep 'de_DE.UTF-8' /etc/locale.gen
          then sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen
        else
          echo 'de_DE.UTF-8 UTF-8' >> /etc/locale.gen
        fi
        echo "Execute locale-gen ..."
        locale-gen
        echo "Now current available locales:"
        locale -a

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
