---
name: Installing necessary PIP modules and Linting tools
author: Frank Brehm
description: Installing necessary PIP modules and Linting tools

inputs:
  install_pytest:
    description: Should pytest be installed.
    required: false
    default: false
  install_linter_tools:
    description: Should linter tools like pylint, flake8, shellcheck a.s.o be installed.
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Show Python Environment
      id: show-python
      shell: bash
      run: |
        echo "Current Python version:"
        python3 --version
    - name: Creating Python virtual environment
      id: create-venv
      shell: bash
      run: |
        echo ""
        echo "Creating Python virtual environment '.venv' ..."
        python3 -m venv --system-site-packages .venv
    - name: Upgrading Pip
      id: pip-upgrade
      shell: bash
      run: |
        echo ""
        echo "Activating virtual environment '.venv'."
        source .venv/bin/activate
        echo "Upgrading Pip."
        pip install --upgrade pip
    - name: Install Python Requirements
      id: inst-requirements
      env:
        INSTALL_PYTEST: ${{ inputs.install_pytest }}
        INSTALL_LINTER_TOOLS: ${{ inputs.install_linter_tools }}
        FLIT_ROOT_INSTALL: 1
      shell: bash
      run: |
        echo ""
        echo "Activating virtual environment '.venv'."
        source .venv/bin/activate
        echo "Installing flit with pip ..."
        pip install flit
        echo ""
        echo "Installing all necessary packages with flit ..."
        if [[ "${INSTALL_PYTEST}" == false ]] ; then
            echo "Installing linting modules ..."
            flit install --only-deps --deps production --extras lint --python .venv/bin/python3
        fi
        if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
            echo "Installing test modules ..."
            flit install --only-deps --deps production --extras testing --python .venv/bin/python3
        fi
    - name: Show installed Python modules
      id: show-py-modules
      env:
        USE_POETRY: ${{ inputs.use_poetry }}
      shell: bash
      run: |
        echo ""
        echo "All installed Python modules:"
        source .venv/bin/activate
        pip3 list --format columns

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
