---
name: Installing necessary PIP modules and Linting tools
author: Frank Brehm
description: Installing necessary PIP modules and Linting tools

inputs:
  install_pytest:
    description: Should pytest be installed.
    required: false
    default: false
  install_linter_tools:
    description: Should linter tools like pylint, flake8, shellcheck a.s.o be installed.
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Show Python Environment
      id: show-python
      shell: bash
      run: |
        echo "Current Python version:"
        python3 --version
    - name: Upgrading Pip
      id: pip-upgrade
      shell: bash
      run: |
        echo ""
        echo "Upgrading Pip."
        pip install --upgrade pip
    - name: Install Python Requirements
      id: inst-requirements
      env:
        INSTALL_PYTEST: ${{ inputs.install_pytest }}
        INSTALL_LINTER_TOOLS: ${{ inputs.install_linter_tools }}
      shell: bash
      run: |
        echo ""
        echo "Installing poetry with pip ..."
        pip install poetry
        echo ""
        echo "Installing all necessary packages with poetry ..."
        POETRY_OPTS='--no-root --ansi'
        if [[ "${INSTALL_PYTEST}" != false ]] ; then
            POETRY_OPTS+=" --only=test"
        fi
        if [[ "${INSTALL_LINTER_TOOLS}" != false ]] ; then
            POETRY_OPTS+=" --only=dev"
        fi
        echo "Poetry install options: '${POETRY_OPTS}'"
        poetry install ${POETRY_OPTS}
    - name: Show installed Python modules
      id: show-py-modules
      env:
        USE_POETRY: ${{ inputs.use_poetry }}
      shell: bash
      run: |
        echo "All installed Python modules:"
        poetry run pip list --format columns

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
