---

name: Preparing GPG
author: Frank Brehm
description: This action prepares gpg for signing files without entering a password

inputs:
  public_key:
    description: "This is the exported public GPG key"
    required: true
  private_key:
    description: "This is the exported private key"
    required: true
  key_password:
    description: "This is the password of the imported private key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Importing public GPG key
      shell: bash
      env:
        PUBLIC_KEY: ${{ inputs.public_key }}
        KEY_PASSWORD: ${{ inputs.key_password }}
      run: |
        echo "Importing public GPG key ..."
        echo "${PUBLIC_KEY}" | gpg --import
        echo
        gpg --list-public-keys
    - name: Importing private GPG key
      shell: bash
      env:
        PRIVATE_KEY: ${{ inputs.private_key }}
        KEY_PASSWORD: ${{ inputs.key_password }}
      run: |
        echo "Importing private GPG key ..."
        echo "${PRIVATE_KEY}" | gpg --import --batch --pinentry-mode loopback --passphrase "${KEY_PASSWORD}"
        echo
        gpg --list-secret-keys
    - name: Creating GPG key file
      shell: bash
      env:
        KEY_PASSWORD: ${{ inputs.key_password }}
      run: |
        PASSWORD_FILE_REL="${GPG_PASSWORD_FILE:-.private/uhu.txt}"
        PASSWORD_FILE_ABS=$( readlink --canonicalize-missing "${PASSWORD_FILE_REL}" )
        PASSWORD_DIR=$( dirname "${PASSWORD_FILE_ABS}" )
        if [[ ! -d "${PASSWORD_DIR}" ]] ; then
            echo
            mkdir --parents --verbose --mode 0700 "${PASSWORD_DIR}"
        fi
        echo
        echo "Creating password file '${PASSWORD_FILE_ABS}' ..."
        echo "${KEY_PASSWORD}" > "${PASSWORD_FILE_ABS}"
        chmod --verbose 0600 "${PASSWORD_FILE_ABS}"
        echo
        ls -l --directory --color=auto "${PASSWORD_DIR}" "${PASSWORD_FILE_ABS}"
    - name: Creating GnuPG config
      shell: bash
      run: |
        PASSWORD_FILE_REL="${GPG_PASSWORD_FILE:-.private/uhu.txt}"
        PASSWORD_FILE_ABS=$( readlink --canonicalize-missing "${PASSWORD_FILE_REL}" )
        GPG_DIR="${HOME}/.gnupg"
        GPG_CONF="${GPG_DIR}/gpg.conf"
        if [[ ! -d "${GPG_DIR}" ]] ; then
            echo
            mkdir --parents --verbose --mode 0700 "${GPG_DIR}"
        fi
        if [[ ! -f "${GPG_CONF}" ]] ; then
            echo
            touch "${GPG_CONF}"
            chmod --verbose 0600 "${GPG_CONF}"
        fi
        echo
        printf "Setting default Key-Id "
        if grep -q -P '^\s*default-key\s' "${GPG_CONF}" ; then
            echo "by substituting old value ..."
            sed -i -e "s/[ 	]*default-key[ 	].*/default-key ${GPG_KEY_ID}/i" "${GPG_CONF}"
        else
            echo "by setting new value ..."
            echo "default-key ${GPG_KEY_ID}" >> "${GPG_CONF}"
        fi
        echo
        printf "Setting batch mode "
        if grep -q -P '^\s*batch\s*$' "${GPG_CONF}" ; then
            echo "- already set."
        else
            echo "by setting mode."
            echo "batch" >> "${GPG_CONF}"
        fi
        printf "Setting Pinentry mode "
        if grep -q -P '^\s*pinentry-mode\s' "${GPG_CONF}" ; then
            echo "by substituting old value ..."
            sed -i -e "s/[ 	]*pinentry-mode[ 	].*/pinentry-mode loopback/i" "${GPG_CONF}"
        else
            echo "by setting new value ..."
            echo "pinentry-mode loopback" >> "${GPG_CONF}"
        fi
        echo
        printf "Setting passphrase-file "
        if grep -q -P '^\s*passphrase-file\s' "${GPG_CONF}" ; then
            echo "by substituting old value ..."
            sed -i -e "s/[ 	]*passphrase-file[ 	].*/passphrase-file ${PASSWORD_FILE_ABS}/i" "${GPG_CONF}"
        else
            echo "by setting new value ..."
            echo "passphrase-file ${PASSWORD_FILE_ABS}" >> "${GPG_CONF}"
        fi
        echo
        echo "Modified '${GPG_CONF}':"
        grep -P -v '^\s*(#|$)' "${GPG_CONF}"


# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
