---

name: "Building OS packages"

on:
  push:
    branches-ignore:
      - dev-**
      - dev/**
      - hf**

env:
  DEBFULLNAME: 'Frank Brehm'
  DEBEMAIL: 'frank@brehm-online.com'
  USED_TIMEZONE: 'Europe/Berlin'
  NOTIFY_ADDRESS: 'frank@brehm-online.com,frank.brehm@pixelpark.com'
  SENDER_ADDRESS: 'Frank Brehm <frank@brehm-online.com>'
  SMTP_SERVER_ADDRESS: 'mail.uhu-banane.net'
  SMTP_SERVER_PORT: 587
  PKG_NAME: 'fb_logging'

jobs:

  test:
    runs-on: ubuntu-latest
    name: Executing Python tests
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.6', '3.7', '3.8', '3.9' ]
    container: python:${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Show Environment
        run: python --version
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/install-pip-modules
      - name: Install PyTest with pip
        run: |
          pip install --upgrade --upgrade-strategy eager pytest
          pip list --format columns
      - name: Executing PyTest
        run: pytest --verbose

  linter:
    runs-on: ubuntu-latest
    name: Executing Linters
    container: python:3.9
    env:
      FLAKE8_MAX_LINE_LENGTH: 99
      FLAKE8_MAX_COMPLEXITY: 20
      FLAKE8_IGNORE_ERRORS: 'E226,E302,E41,E402'
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/install-pip-modules
#      - name: Install shellcheck and yamllint
#        run: apt install --yes shellcheck yamllint
      - name: Install flake8 and pylint
        run: |
          pip install --upgrade --upgrade-strategy eager flake8 pylint
          pip list --format columns
      - name: Execute Flake 8
        run: >
          flake8
          --max-line-length=$FLAKE8_MAX_LINE_LENGTH
          --max-complexity=$FLAKE8_MAX_COMPLEXITY
          --ignore=$FLAKE8_IGNORE_ERRORS
          lib
#          bin
#      - name: Execute Shellcheck
#        run: >
#          shellcheck -x compile-xlate-msgs.sh test.py-*.sh test.rc
#          test/call_script.sh test/call_sleep.sh update-env.sh xtract-xlate-msgs.sh
#      - name: Execute Yamllint
#        run: yamllint -c yamllint.yaml .gitlab-ci.yml

  build_debian_sources:
    runs-on: ubuntu-latest
    name: Building Debian Source Packages
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || startsWith( github.ref, 'refs/tags/' ) }}
    container: debian:bullseye
    needs:
      - linter
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/debian-install-buildenv
      - name: Debian build
        run: |
          echo "y" | debuild -S -i -us -uc
          ls -lA --color=always ..
          mkdir -pv debian/pkgs/src
          mv -vi ../*.dsc ../*.tar.* ../*.build* ../*.changes debian/pkgs/src
          ls -lA --color=always debian/pkgs/*/*
      - name: 'Upload Source Package'
        uses: actions/upload-artifact@v2
        with:
          name: debian_sources
          path: debian/pkgs/*/*
          retention-days: 15

  build_debian_bin:
    runs-on: ubuntu-latest
    name: Building Debian Binary Packages
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || startsWith( github.ref, 'refs/tags/' ) }}
    needs:
      - linter
    strategy:
      fail-fast: false
      matrix:
        include:
          - distributor: 'Debian'
            os_codename: 'buster'
            os_release: '10'
            container: 'debian:buster'
            version_prefix: 'deb10'
            compat: '11'
          - distributor: 'Debian'
            os_codename: 'bullseye'
            os_release: '11'
            container: 'debian:bullseye'
            version_prefix: 'deb11'
            compat: '12'
          - distributor: 'Ubuntu'
            os_codename: 'bionic'
            os_release: '18.04'
            container: 'ubuntu:bionic'
            version_prefix: 'ubuntu18.04'
            compat: '11'
          - distributor: 'Ubuntu'
            os_codename: 'focal'
            os_release: '20.04'
            container: 'ubuntu:focal'
            version_prefix: 'ubuntu20.04'
            compat: '12'
    env:
      COMPAT: ${{ matrix.compat }}
      DISTRIBUTOR: ${{ matrix.distributor }}
      OS_CODENAME: ${{ matrix.os_codename }}
      OS_RELEASE: ${{ matrix.os_release }}
      VERSION_PREFIX: ${{ matrix.version_prefix }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Setting timezone
        if: ${{ matrix.distributor == 'Ubuntu' }}
        run: |
          echo "Setting system timezone to ${USED_TIMEZONE} ..."
          ln -fvs /usr/share/zoneinfo/${USED_TIMEZONE} /etc/localtime
          export DEBIAN_FRONTEND=noninteractive
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/debian-install-buildenv
      - name: Updating Changelog
        run: |
          export PKG_VERSION=$( ./get-debian-version )
          export BUILD_VERSION="${PKG_VERSION}+${VERSION_PREFIX}"
          BUILDER="${DEBFULLNAME} <${DEBEMAIL}>"
          echo "Version to build: ${BUILD_VERSION} - Builder: ${BUILDER}"
          debchange --newversion "${BUILD_VERSION}" --force-bad-version --distribution "${OS_CODENAME}" --urgency medium "Build for ${DISTRIBUTOR} ${OS_RELEASE} - ${OS_CODENAME}"
          head -n 5 debian/changelog
      - name: Debian build
        run: |
          echo "Setting debian/compat to ${COMPAT}"
          echo "${COMPAT}" > debian/compat
          echo "y" | debuild -b -i -us -uc
          ls -lA --color=always ..
          mkdir -pv debian/pkgs/src debian/pkgs/${VERSION_PREFIX}
          mv -vi ../*.deb debian/pkgs/${VERSION_PREFIX}
          mv -vi ../*.build* debian/pkgs/src
          ls -lA --color=always debian/pkgs/*/*
      - name: 'Upload Source Package'
        uses: actions/upload-artifact@v2
        with:
          name: debian_bin_pkgs_${{ matrix.version_prefix }}
          path: debian/pkgs/*/*
          retention-days: 15

  build_rpm:
    runs-on: ubuntu-latest
    name: Building RPM packages for Enterprise Linux
    # if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || startsWith( github.ref, 'refs/tags/' ) }}
    needs:
      - linter
    strategy:
      fail-fast: true
      matrix:
        el_version: ['7', '8']
    container: centos:${{ matrix.el_version }}
    env:
      EL_VERSION: ${{ matrix.el_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Chacking locales
        shell: bash
        run: |
          locale -a
          locale
          export LC_ALL=en_US.utf8
          locale
      - name: Install EPEL repo
        shell: bash
        run: yum --assumeyes install epel-release
      - name: Upgrade all packages
        shell: bash
        run: |
          yum clean all
          yum makecache
          echo "Upgrading all packages"
          yum --assumeyes upgrade
      - name: Install Python 3
        shell: bash
        run: |
          if [[ "${EL_VERSION}" == "7" ]] ; then PY_VERSION="36" ; else PY_VERSION="38"; fi
          echo "Installing Python ${PY_VERSION} ..."
          yum --assumeyes install python${PY_VERSION} python${PY_VERSION}-setuptools python${PY_VERSION}-pip python${PY_VERSION}-devel
          ls -l --color=always /bin/python* /bin/pip* || true
          pip3 list
      - name: Installing build tools
        shell: bash
        run: |
          yum --assumeyes install gnupg2 rpm-build tree
      - name: Create build environment
        shell: bash
        run: |
          mkdir -pv rpmdir
          mkdir -pv rpmdir/SOURCES
          ODIR=$(pwd)
          ROOT_OBJECTS=$( ls -A1 | egrep -vw ".git|rpmdir" )
          echo "Root objects:"; for o in ${ROOT_OBJECTS}; do echo " * ${o}"; done
          PKG_VERSION=$( ./get-rpm-version )
          PKG_RELEASE=$( ./get-rpm-release )
          echo "Version to build: ${PKG_VERSION}-${PKG_RELEASE}"
          mkdir -pv "rpmdir/SOURCES/python_fb_tools-${PKG_VERSION}"


  notify_success:
    runs-on: ubuntu-latest
    name: Sending Success message
    needs:
      - 'build_debian_sources'
      - 'build_debian_bin'
    steps:
      - name: Sending message
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: ${{ env.SMTP_SERVER_ADDRESS }}
          server_port: ${{ env.SMTP_SERVER_PORT }}
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Github Workflow ${{ github.workflow }} of ${{ github.repository }} was successful.
          # email body as text
          body: |
            Github Actions Workflow ${{ github.workflow }} of ${{ github.repository }} was successful.
            Commiter: ${{ github.actor }}

            Cheers Frank
          # comma-separated string, send email to
          to: ${{ env.NOTIFY_ADDRESS }}
          # from email name
          from: ${{ env.SENDER_ADDRESS }}

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
