---

name: "Building OS packages."

on:
  push:
    branches-ignore:
      - /^dev-.*$/
      - /^dev\/.*$/
      - /^hf.*$/

env:
  DEBFULLNAME: 'Frank Brehm'
  DEBEMAIL: 'frank@brehm-online.com'
  USED_TIMEZONE: 'Europe/Berlin'

jobs:

  test:
    runs-on: ubuntu-latest
    name: Executing Python tests
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.6', '3.7', '3.8', '3.9' ]
    container: python:${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Show Environment
        run: python --version
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/install-pip-modules
      - name: Install PyTest with pip
        run: |
          pip install --upgrade --upgrade-strategy eager pytest
          pip list --format columns
      - name: Executing PyTest
        run: pytest --verbose

  linter:
    runs-on: ubuntu-latest
    name: Executing Linters
    container: python:3.9
    env:
      FLAKE8_MAX_LINE_LENGTH: 99
      FLAKE8_MAX_COMPLEXITY: 20
      FLAKE8_IGNORE_ERRORS: 'E226,E302,E41,E402'
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-debian-container
      - uses: ./.github/actions/install-pip-modules
#      - name: Install shellcheck and yamllint
#        run: apt install --yes shellcheck yamllint
      - name: Install flake8 and pylint
        run: |
          pip install --upgrade --upgrade-strategy eager flake8 pylint
          pip list --format columns
      - name: Execute Flake 8
        run: >
          flake8
          --max-line-length=$FLAKE8_MAX_LINE_LENGTH
          --max-complexity=$FLAKE8_MAX_COMPLEXITY
          --ignore=$FLAKE8_IGNORE_ERRORS
          lib
#          bin
#      - name: Execute Shellcheck
#        run: >
#          shellcheck -x compile-xlate-msgs.sh test.py-*.sh test.rc
#          test/call_script.sh test/call_sleep.sh update-env.sh xtract-xlate-msgs.sh
#      - name: Execute Yamllint
#        run: yamllint -c yamllint.yaml .gitlab-ci.yml



# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
